name: Env name
on:
  workflow_dispatch:
jobs:
  printing-in-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Print staging
        run: |
          echo "Deploying to ${{ secrets.ENV_NAME }} environment..."
